- async函数返回一个promise对象
async函数内部return语句返回的值，会成为then方法回调函数的参数
```
    async function f() {
        return 'hello'
    }
    f().then(v => console.log(v)) // hello world  函数f内部return命令返回的值，会被then方法回调函数接收到
```
async函数内部抛出错误，会导致返回的Promise对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到。
```
async function f() {
  throw new Error('出错了');
}

f().then(
  v => console.log(v),
  e => console.log(e)
)
// Error: 出错了
```
- async函数返回的promise对象，必须等到内部的所有await命令的promise对象执行完，才会发生状态改变，也就是说，只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数
- 正常情况下，await命令后面是一个Promise对象。如果不是，会被转成一个立即resolve的Promise对象。
（3）正常情况下，await命令后面是一个Promise对象。如果不是，会被转成一个立即resolve的Promise对象。
自然茧:
https://zhuanlan.zhihu.com/p/102442557

自然茧:
https://blog.csdn.net/Gear_World/article/details/109645660
